apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-admin
  template:
    metadata:
      labels:
        app: mysql-admin
    spec:
      containers:
      - name: mysql-admin
        image: adminer
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-admin-service
spec:
  selector:
    app: mysql-admin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
